version: "3.9"

volumes:
  data-node:

networks:
  backend-networks:

services:
#  s3-ninja:
#    image: scireum/s3-ninja:7.0
#    valumes:
#      - data-s3:/home/sirius/data
#    networks:
#      - backend-network
#    ports:
#      - 9444:9000

  node:
    image: node:16.2.0
    ports:
      - 3000:3000
    volumes:
      - data-node:/node
      - ./index.js:/index.js
      - ./Public:/Public
    command: node index.js

#  docker-compose up (for run)